config/routes.rb
Rails.application.routes.draw do
  get 'quotes/new'
  resources :quotes
  post 'checkout/create' => 'checkouts#create', as: "checkout_create"
  post "/stripe_webhooks",to:"webhooks#create"
  # get "checkouts", to: "checkouts#show"
  # get "billing", to: "billing#show"

    resources :category do
        resources  :subcategory do
          resources :childs 
        end
    end


  resources :vendors
  resources :bookings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # patch '/users', to: "registrations#update"
  # delete '/users', to: "registrations@destroy"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' ,registrations:"registrations"} do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/edit' => 'devise/sessions#edit'
    # patch 'users/update'=> 'devise/sessions#update'
  end


  # devise_for :users,:controllers=>{registrations:"registrations"} do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  resources :events
  root to: 'homes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :place,:event_date,presence: true
  # validates_uniqueness_of :event_date, :on => :message => "must be unique"
 
  belongs_to :event 
  belongs_to :vendor
  belongs_to :user
  belongs_to :subcategory
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  # has_and_belongs_to_many :subcategories
  has_many :categorysubcategories
  has_many :subcategories, through: :categorysubcategories
  belongs_to :event
  has_many :bookings
end

app/models/categorysubcategory.rb
class Categorysubcategory < ApplicationRecord
  belongs_to :category
  belongs_to :subcategory
end

app/models/checkout.rb
class Checkout < ApplicationRecord
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :subcategory
end

app/models/event.rb
class Event < ApplicationRecord
    #  has_ancestry ancestry_column: :parent_id ## if you've used a different column name
    belongs_to :vendor
    
    has_many :EventVendors
    has_many :vendors, through: :EventVendors
    has_many :bookings, dependent: :destroy
    has_many :categories
end

app/models/event_vendor.rb
class EventVendor < ApplicationRecord
  belongs_to :event
  belongs_to :vendor
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :name,:email,:phone,:date,:budget,:comment,:event_id,presence: true
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  # belongs_to :category
  # has_and_belongs_to_many :categories
  has_many :categorysubcategories
  has_many :categories,through: :categorysubcategories, class_name: "Categorysubcategory", foreign_key: 'category_id'
  has_many :childs
  has_many :bookings

  after_create do
    product=Stripe::Product.create(name: name)
    price = Stripe::Price.create(product: product,unit_amount: self.price.to_i*100,currency:"inr")
    update(stripe_product_id: product.id,stripe_price_id: price.id)
 end
 
end

app/models/user.rb
class User < ApplicationRecord
  # include Pay::Billable
  # pay_customer
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and 
  attr_accessor :role

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  after_create :set_stripe_id

  # after_update :crop_image
  after_update :crop_image, if: :image_present


  validates :email,:fname,:lname,:dob, presence: true
  has_many :vendors
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable,:omniauthable, :registerable,
         :recoverable, :rememberable, :validatable
         
  mount_uploader :image, ImageUploader
  
  enum role: {"user"=>0, "vendor"=>1, "admin"=>2}

  def crop_image 
    binding.pry
    image.recreate_versions! if crop_x.present? && self.image.size > 0
  end

  def image_present
    self.image.size > 0
  end


  def self.from_omniauth(auth)
    
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.fname = auth.info.name   # assuming the user model has a name
      # user.image =s auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end


  private
  def set_stripe_id
    debugger
    if self.role == 'user'
      customer = Stripe::Customer.create(email:email, name:fname)
      self.update(stripe_customer_id: customer.id)
    end
  end


end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :user
  
  has_many :bookings, dependent: :destroy
  # has_many :events
  has_many :EventVendors
  has_many :events, through: :EventVendors

  validates :description,:address,:phone,:nearest_landmark,:website,:established_in, presence: true
  validates :user_id, uniqueness: true 
end

app/controllers/childs_controller.rb
class ChildsController < ApplicationController

  def index
    @subcategory = Subcategory.find(params[:subcategory_id])
    @child = @subcategory.childs
    respond_to do |format|
      format.js
    end
  end

  def show
    
  end

  def new
  end

  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.all;
    
    # @event = Event.where(parent_id: params[:parent_id]).to_a
 


  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_vendor

  def index
    # debugger
    @booking = Booking.all
    @vendor
    @event = Event.all
  end

  private

  def set_vendor
    if(user_signed_in? && current_user.role == "vendor")
      @vendor = Vendor.find_by(:user_id => current_user.id)
    end
  end


end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.create(quote_params)
    event = Event.find_by(id: params.require(:quote).fetch(:event_id))
    # binding.pry
    if @quote.save
      event.vendors.each do |pass|
        # binding.pry
        QuoteMailer.invitation_create(pass,@quote).deliver_now!
      end
      flash[:notice] =  "Email Successfully Sent"
      redirect_to root_path
    else
      render :new
    end
  end
  
  private
  def quote_params
    params.require(:quote).permit(:name,:email,:phone,:date,:budget,:guest,:comment,:event_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/quotes/new.html.erb
<section class="h-100 bg-dark">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col">
        <div class="card card-registration my-4">
          <div class="row g-0">
            <div class="col-xl-6 d-none d-xl-block">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/img4.webp"
                alt="Sample photo" class="img-fluid"
                style="border-top-left-radius: .25rem; border-bottom-left-radius: .25rem;" />
            </div>
            <div class="col-xl-6">
              <div class="card-body p-md-5 text-black", id = "form">
                <h3 class="mb-5 text-uppercase">Get A Quote</h3>
                    <%= form_with(model: @quote,:validate=> true,url: quotes_url) do |form| %>
                <div class="row">
                        <div class="modal-body">
                              
                  <div class="col-md-6 mb-4">
                        <div class="form-outline">
                          <%= form.label :name,class: "form-label"%>
                          <%= form.text_field :name,class: "form-control form-control-lg" %>
                          <%# <input type="text" id="form3Example1m" class="form-control form-control-lg" />
                          <label class="form-label" for="form3Example1m">First name</label> %>
                        </div>
                  </div>
                  <div class="col-md-6 mb-4">
                        <div class="form-outline">
                          <%= form.label :email,class: "form-label"%>
                          <%= form.email_field :email,class: "form-control form-control-lg" %>
                          <%= form.label :phone,class: "form-label"%>
                          <%= form.telephone_field :phone,class: "form-control form-control-lg" %>
                          <%# <input type="text" id="form3Example1n" class="form-control form-control-lg" />
                          <label class="form-label" for="form3Example1n">Phone number </label> %>
                        </div>
                  </div>
                </div>

                <div class="row">
                      <div class="col-md-6 mb-4">
                            <div class="form-outline">
                              <%= form.label :date,class: "form-label"%>
                              <%= form.date_field :date,class: "form-control form-control-lg" %>
                              <%# <input type="text" id="form3Example1m1" class="form-control form-control-lg" />
                              <label class="form-label" for="form3Example1m1">Date</label> %>
                            </div>
                      </div>
                      <div class="col-md-6 mb-4">
                            <div class="form-outline">
                              <%# <input type="text" id="form3Example1n1" class="form-control form-control-lg" />
                              <label class="form-label" for="form3Example1n1">Event</label> %>
                              <%= form.label :Event%>
                              <%= form.collection_select :event_id, Event.order(:name), :id, :name %>
                            </div>
                      </div>
                </div>

                        <%# <div class="form-outline mb-4">
                          <input type="text" id="form3Example8" class="form-control form-control-lg" />
                          <label class="form-label" for="form3Example8">Address</label>
                        </div> %>

                <div class="d-md-flex justify-content-start align-items-center mb-4 py-2">

                        <%# <h6 class="mb-0 me-4">Gender: </h6>

                        <div class="form-check form-check-inline mb-0 me-4">
                          <input class="form-check-input" type="radio" name="inlineRadioOptions" id="femaleGender"
                            value="option1" />
                          <label class="form-check-label" for="femaleGender">Female</label>
                        </div>

                  <div class="form-check form-check-inline mb-0 me-4">
                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="maleGender"
                          value="option2" />
                        <label class="form-check-label" for="maleGender">Male</label>
                  </div>

                  <div class="form-check form-check-inline mb-0">
                        <input class="form-check-input" type="radio" name="inlineRadioOptions" id="otherGender"
                          value="option3" />
                        <label class="form-check-label" for="otherGender">Other</label>
                  </div> %>

                </div>

                <%# <div class="row">
                  <div class="col-md-6 mb-4">

                    <select class="select">
                      <option value="1">State</option>
                      <option value="2">Option 1</option>
                      <option value="3">Option 2</option>
                      <option value="4">Option 3</option>
                    </select>

                  </div>
                  <div class="col-md-6 mb-4">

                    <select class="select">
                      <option value="1">City</option>
                      <option value="2">Option 1</option>
                      <option value="3">Option 2</option>
                      <option value="4">Option 3</option>
                    </select>

                  </div>
                </div> %>

                <div class="form-outline mb-4">
                  <%= form.label :Budget_Per_Person,class: "form-control form-control-lg"%>
                  <%= form.range_field :budget, in: 1..100, id: "form3Example9",class:"form-control form-control-lg" %>
                  <%# <input type="text" id="form3Example9" class="form-control form-control-lg" />
                  <label class="form-label" for="form3Example9">DOB</label> %>
                </div>

                <div class="form-outline mb-4">
                  <%= form.label :number_of_guest,class: "form-control form-control-lg"%>
                  <%= form.number_field :guest, in: 1.0..20.0, step: 1,class:"form-control form-control-lg" %>

                  <%# <input type="text" id="form3Example90" class="form-control form-control-lg" />
                  <label class="form-label" for="form3Example90">Number Of Guest</label> %>
                </div>

                <div class="form-outline mb-4">
                  <%= form.label :comment,class: "form-control form-control-lg"%>
                  <%= form.text_area :comment, size: "70x5" ,class: "form-control form-control-lg"%>

                  <%# <input type="text" id="form3Example99" class="form-control form-control-lg" />
                  <label class="form-label" for="form3Example99">Comment</label> %>
                </div>

                <div class="d-flex justify-content-end pt-3">
                  <button type="button" class="btn btn-light btn-lg">Reset all</button>
                  <%= form.submit %>
                  <%# <button type="button" class="btn btn-warning btn-lg ms-2">Submit form</button> %>
                </div>

                <% end %>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<style>
.card-registration .select-input.form-control[readonly]:not([disabled]) {
  font-size: 1rem;
line-height: 2.15;
padding-left: .75em;
padding-right: .75em;
}
.card-registration .select-arrow {
top: 13px;
}



.field_with_errors {
  display: inline;
}

.field_with_errors .message {
  color: #D00;
  padding-left: 5px;
  font-size: 12px;
}


</style>