config/routes.rb
Rails.application.routes.draw do
  get 'quotes/new'
  resources :quotes
  post 'checkout/create' => 'checkouts#create', as: "checkout_create"
  post "/stripe_webhooks",to:"webhooks#create"
  # get "checkouts", to: "checkouts#show"
  # get "billing", to: "billing#show"

    resources :category do
        resources  :subcategory do
          resources :childs 
        end
    end


  resources :vendors
  resources :bookings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # patch '/users', to: "registrations#update"
  # delete '/users', to: "registrations@destroy"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' ,registrations:"registrations"} do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/edit' => 'devise/sessions#edit'
    # patch 'users/update'=> 'devise/sessions#update'
  end


  # devise_for :users,:controllers=>{registrations:"registrations"} do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  resources :events
  root to: 'homes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :place,:event_date,presence: true
  # validates_uniqueness_of :event_date, :on => :message => "must be unique"
 
  belongs_to :event 
  belongs_to :vendor
  belongs_to :user
  belongs_to :subcategory
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  # has_and_belongs_to_many :subcategories
  has_many :categorysubcategories
  has_many :subcategories, through: :categorysubcategories
  belongs_to :event
  has_many :bookings
end

app/models/categorysubcategory.rb
class Categorysubcategory < ApplicationRecord
  belongs_to :category
  belongs_to :subcategory
end

app/models/checkout.rb
class Checkout < ApplicationRecord
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :subcategory
end

app/models/event.rb
class Event < ApplicationRecord
    #  has_ancestry ancestry_column: :parent_id ## if you've used a different column name
    belongs_to :vendor
    
    has_many :EventVendors
    has_many :vendors, through: :EventVendors
    has_many :bookings, dependent: :destroy
    has_many :categories
end

app/models/event_vendor.rb
class EventVendor < ApplicationRecord
  belongs_to :event
  belongs_to :vendor
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :name,:email,:phone,:date,:budget,:comment,:event_id,presence: true
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  # belongs_to :category
  # has_and_belongs_to_many :categories
  has_many :categorysubcategories
  has_many :categories,through: :categorysubcategories, class_name: "Categorysubcategory", foreign_key: 'category_id'
  has_many :childs
  has_many :bookings

  after_create do
    product=Stripe::Product.create(name: name)
    price = Stripe::Price.create(product: product,unit_amount: self.price.to_i*100,currency:"inr")
    update(stripe_product_id: product.id,stripe_price_id: price.id)
 end
 
end

app/models/user.rb
class User < ApplicationRecord
  # include Pay::Billable
  # pay_customer
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and 
  attr_accessor :role

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  after_create :set_stripe_id

  # after_update :crop_image
  after_update :crop_image, if: :image_present


  validates :email,:fname,:lname,:dob, presence: true
  has_many :vendors
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable,:omniauthable, :registerable,
         :recoverable, :rememberable, :validatable
         
  mount_uploader :image, ImageUploader
  
  enum role: {"user"=>0, "vendor"=>1, "admin"=>2}

  def crop_image 
    binding.pry
    image.recreate_versions! if crop_x.present? && self.image.size > 0
  end

  def image_present
    self.image.size > 0
  end


  def self.from_omniauth(auth)
    
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.fname = auth.info.name   # assuming the user model has a name
      # user.image =s auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end


  private
  def set_stripe_id
    debugger
    if self.role == 'user'
      customer = Stripe::Customer.create(email:email, name:fname)
      self.update(stripe_customer_id: customer.id)
    end
  end


end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :user
  
  has_many :bookings, dependent: :destroy
  # has_many :events
  has_many :EventVendors
  has_many :events, through: :EventVendors

  validates :description,:address,:phone,:nearest_landmark,:website,:established_in, presence: true
  validates :user_id, uniqueness: true 
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # before_action :authenticate_user! , :[:create,:new]
  skip_before_action :verify_authenticity_token, only: [:create, :destroy]
  def index
    @bookings = Booking.all
    
    @user_booking = current_user.bookings.to_a
    # binding.pry
  end

  def new
    # binding.pry
    @booking = Booking.new(booking_params)
    # respond_to do |format|
    #   format.js
    # end
  end

  def create
    # @user = current_user
    @booking = Booking.new
    @booking.vendor_id= params.require(:booking).fetch(:vendor_id)
    @booking.user_id= params.require(:booking).fetch(:user_id)
    @booking.event_id= params.require(:booking).fetch(:event_id)
    @booking.place=params.require(:booking).fetch(:place)
    @booking.event_date= params.require(:booking).fetch(:event_date)
    @booking.category_id= params.require(:booking).fetch(:category_id)
    @booking.subcategory_id= params.require(:booking).fetch(:subcategory_id)
    # debugger
    
    # binding.pry
    if @booking.save
      respond_to do |format|
        format.js 
      end
      # redirect_to booking_url(@booking)
    else
      render :new 
    end
  end

  def show
    # debugger
    @booking = Booking.find(params[:id])
  end

  def destroy
    binding.pry
    @booking = Booking.find(params[:id])
    

    if @booking.destroy
      redirect_to root_path
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end


  def update
    @booking =Booking.find(params[:id])
    @booking.place=params.require(:booking).fetch(:place)
    @booking.event_date= params.require(:booking).fetch(:event_date)
    @booking.event_date= params.require(:booking).fetch(:category_id)
    @booking.event_date= params.require(:booking).fetch(:subcategory_id)

    if @booking.update(booking_params)
      redirect_to root_path
    else
      render :edit,status: :unprocessable_entity
    end
  end
    
  private
    def booking_params
      params.permit(:user_id,:event_id,:vendor_id,:event_date,:place,:category_id, :subcategory_id)
    end

end

app/controllers/childs_controller.rb
class ChildsController < ApplicationController

  def index
    @subcategory = Subcategory.find(params[:subcategory_id])
    @child = @subcategory.childs
    respond_to do |format|
      format.js
    end
  end

  def show
    
  end

  def new
  end

  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.all;
    
    # @event = Event.where(parent_id: params[:parent_id]).to_a
 


  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_vendor

  def index
    # debugger
    @booking = Booking.all
    @vendor
    @event = Event.all
  end

  private

  def set_vendor
    if(user_signed_in? && current_user.role == "vendor")
      @vendor = Vendor.find_by(:user_id => current_user.id)
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/bookings/_index.html.erb
<h1>Booking Event</h1>

<h5>Booking</h5>
<% if @booking.nil? %>
<p>No Booking Available</p>
<%end%>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">User_name</th>
      <th scope="col">Vendor_name</th>
      <th scope="col">Event_name</th>
      <th scope="col">Date</th>
      <th scope="col">Event_name</th>
      <th scope="col">Action</th>

    </tr>
  </thead>
  <tbody>
  <% @booking.each do |b|%>
    <tr>
      <th scope="row">1</th>
      <td><%= b.user.fname %></td>
      <td><%= b.vendor.user.fname%>  <%= b.vendor.user.lname%></td>
      <td><%= b.event.name%> </td>
      <td><%= b.event_date%></td>
      <td><%= b.place%></td>
      <td><%= link_to "Show",booking_path(b.id),class: "btn btn-info"%>
      <td><%= link_to "Update",edit_booking_path(b.id),class: "btn btn-info"%>
      
      <td><%= link_to "Delete",booking_path(b.id),method: :delete, class:"btn btn-success"%>
    </tr>
    <%end%>
  </tbody>
</table>

app/views/bookings/_new.html.erb
<h1>Booking Event</h1>

<%= form_for(@booking , remote: true) do |form| %>
 <div class="modal-body">
 <%=form.hidden_field :vendor_id, :vendor_id => :vendor_id%>
 <%=form.hidden_field :event_id, :event_id => :event_id%>
 <%=form.hidden_field :user_id, :user_id => @current_user%>
                        <%= form.label :Event_Date%>
                        <%= form.date_field :event_date %>


                        <%= form.label :place%>
                        <%= form.text_field :place %>

</div>

      <div class="modal-footer">
                        <%= form.submit "Submit",class:"btn btn-primary"%>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>

<% end %>

app/views/bookings/_show.html.erb
Booking#show

Booking_id:    <%=@booking.id%><br>
Username: <%=@booking.user.fname%><br>
Event_location: <%= @booking.place%><br>
Event_date: <%= @booking.event_date%><br>
Vendor_name: <%= @booking.vendor.user.fname%><br>
Vendor_phone-number:  <%= @booking.vendor.phone%><br>
vendor(Web-address): <%= @booking.vendor.website %><br>
Price (INR): <%= @booking.subcategory.price%>
<td><%= link_to "Pay",checkout_create_path(booking_id: @booking.id),method: :post,class:"btn btn-success",remote: true if @booking.status==false%></td>
  

app/views/bookings/create.js.erb
$("#booking").html("<%=escape_javascript(render "show",:booking=>@booking) %>");

app/views/bookings/edit.html.erb
<h1>Booking Event</h1>

<%= form_for(@booking , remote: true) do |form| %>
 <div class="modal-body">
 <%=form.hidden_field :vendor_id, :vendor_id => :vendor_id%>
 <%=form.hidden_field :event_id, :event_id => :event_id%>
 <%=form.hidden_field :user_id, :user_id => @current_user%>
                        <%= form.label :Event_Date%>
                        <%= form.date_field :event_date %>


                        <%= form.label :place%>
                        <%= form.text_field :place %>

</div>

      <div class="modal-footer">
                        <%= form.submit "Submit",class:"btn btn-primary"%>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>

<% end %>

app/views/bookings/index.html.erb
<h1>Booking Event</h1>

<h5>Booking</h5>
<% if @user_booking.nil? %>
<p>No Booking Available</p>
<%end%>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">User_name</th>
      <th scope="col">Vendor_name</th>
      <th scope="col">Event_name</th>
      <th scope="col">Date</th>
      <th scope="col">Event_name</th>
      <th scope ="col">Price</th>
      <th scope = "col">Payment-Status</th>
      <th scope="col">Action</th>

    </tr>
  </thead>
  <tbody>
  <% @user_booking.each do |b|%>
    <tr>
      <th scope="row">1</th>
      <td><%= b.user.fname %></td>
      <td><%= b.vendor.user.fname%>  <%= b.vendor.user.lname%></td>
      <td><%= b.event.name%> </td>
      <td><%= b.event_date%></td>
      <td><%= b.place%></td>
      <td><%= b.subcategory.price%></td>
      <td><%= b.status%></td>
      <td><%= link_to "Show",booking_path(b.id),class: "btn btn-info"%>
      <td><%= link_to "Update",edit_booking_path(b.id),class: "btn btn-info"%>
      
      <td><%= link_to "Delete",booking_path(b.id),method: :delete, class:"btn btn-success"%>
    </tr>
    <%end%>
  </tbody>
</table>
<%# <%= render partial: "index" @user_booking%> %>

app/views/bookings/new.html.erb
<h1>Booking Event</h1>

<%= form_for(@booking,:validate=> true,:remote=>true, :html=>{:id=>"booking"} ) do |form| %>
<div class="modal-body">
 <%=form.hidden_field :category_id, :category_id => :categories_id%>
 <%=form.hidden_field :subcategory_id, :subcategory_id => :subcategories_id%>
 <%=form.hidden_field :vendor_id, :vendor_id => :vendor_id%>
 <%=form.hidden_field :event_id, :event_id => :event_id%>
 <%=form.hidden_field :user_id, :user_id => @current_user%>
                        <%= form.label :Event_Date%>
                        <%= form.date_field :event_date %>


                        <%= form.label :place%>
                        <%= form.text_field :place %>

</div>

      <div class="modal-footer">
                        <%= form.submit "Submit",class:"btn btn-primary"%>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
     
<% end %>
<style>

.field_with_errors {
  display: inline;
}

.field_with_errors .message {
  color: #D00;
  padding-left: 5px;
  font-size: 12px;
}




</style>

app/views/bookings/new.js.erb
<%# $("#newBookingForm").html("<%= escape_javascript render('new',booking:@booking)"); %> %>

app/views/bookings/show.html.erb
Booking#show

Booking_id:    <%=@booking.id%><br>
Username: <%=@booking.user.fname%><br>
Event_location: <%= @booking.place%><br>
Event_date: <%= @booking.event_date%><br>
Vendor_name: <%= @booking.vendor.user.fname%><br>
Vendor_phone-number:  <%= @booking.vendor.phone%><br>
vendor(Web-address): <%= @booking.vendor.website %><br>
Price (INR): <%= @booking.subcategory.price%>
<td><%= button_to "Pay",checkout_create_path(booking_id: @booking.id),remote: true if @booking.status==false%></td>
  