config/routes.rb
Rails.application.routes.draw do
  get 'quotes/new'
  resources :quotes
  post 'checkout/create' => 'checkouts#create', as: "checkout_create"
  post "/stripe_webhooks",to:"webhooks#create"
  # get "checkouts", to: "checkouts#show"
  # get "billing", to: "billing#show"

    resources :category do
        resources  :subcategory do
          resources :childs 
        end
    end


  resources :vendors
  resources :bookings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # patch '/users', to: "registrations#update"
  # delete '/users', to: "registrations@destroy"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' ,registrations:"registrations"} do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/edit' => 'devise/sessions#edit'
    # patch 'users/update'=> 'devise/sessions#update'
  end


  # devise_for :users,:controllers=>{registrations:"registrations"} do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  resources :events
  root to: 'homes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :place,:event_date,presence: true
  # validates_uniqueness_of :event_date, :on => :message => "must be unique"
 
  belongs_to :event 
  belongs_to :vendor
  belongs_to :user
  belongs_to :subcategory
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  # has_and_belongs_to_many :subcategories
  has_many :categorysubcategories
  has_many :subcategories, through: :categorysubcategories
  belongs_to :event
  has_many :bookings
end

app/models/categorysubcategory.rb
class Categorysubcategory < ApplicationRecord
  belongs_to :category
  belongs_to :subcategory
end

app/models/checkout.rb
class Checkout < ApplicationRecord
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :subcategory
end

app/models/event.rb
class Event < ApplicationRecord
    #  has_ancestry ancestry_column: :parent_id ## if you've used a different column name
    belongs_to :vendor
    
    has_many :EventVendors
    has_many :vendors, through: :EventVendors
    has_many :bookings, dependent: :destroy
    has_many :categories
end

app/models/event_vendor.rb
class EventVendor < ApplicationRecord
  belongs_to :event
  belongs_to :vendor
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :name,:email,:phone,:date,:budget,:comment,:event_id,presence: true
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  # belongs_to :category
  # has_and_belongs_to_many :categories
  has_many :categorysubcategories
  has_many :categories,through: :categorysubcategories, class_name: "Categorysubcategory", foreign_key: 'category_id'
  has_many :childs
  has_many :bookings

  after_create do
    product=Stripe::Product.create(name: name)
    price = Stripe::Price.create(product: product,unit_amount: self.price.to_i*100,currency:"inr")
    update(stripe_product_id: product.id,stripe_price_id: price.id)
 end
 
end

app/models/user.rb
class User < ApplicationRecord
  # include Pay::Billable
  # pay_customer
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and 
  attr_accessor :role

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  after_create :set_stripe_id

  # after_update :crop_image
  after_update :crop_image, if: :image_present


  validates :email,:fname,:lname,:dob, presence: true
  has_many :vendors
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable,:omniauthable, :registerable,
         :recoverable, :rememberable, :validatable
         
  mount_uploader :image, ImageUploader
  
  enum role: {"user"=>0, "vendor"=>1, "admin"=>2}

  def crop_image 
    binding.pry
    image.recreate_versions! if crop_x.present? && self.image.size > 0
  end

  def image_present
    self.image.size > 0
  end


  def self.from_omniauth(auth)
    
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.fname = auth.info.name   # assuming the user model has a name
      # user.image =s auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end


  private
  def set_stripe_id
    debugger
    if self.role == 'user'
      customer = Stripe::Customer.create(email:email, name:fname)
      self.update(stripe_customer_id: customer.id)
    end
  end


end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :user
  
  has_many :bookings, dependent: :destroy
  # has_many :events
  has_many :EventVendors
  has_many :events, through: :EventVendors

  validates :description,:address,:phone,:nearest_landmark,:website,:established_in, presence: true
  validates :user_id, uniqueness: true 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_vendor

  def index
    # debugger
    @booking = Booking.all
    @vendor
    @event = Event.all
  end

  private

  def set_vendor
    if(user_signed_in? && current_user.role == "vendor")
      @vendor = Vendor.find_by(:user_id => current_user.id)
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      
    <script src="https://js.stripe.com/v3/"> </script>
    <link rel="stylesheet" href="https://unpkg.com/jcrop/dist/jcrop.css">
    <script src="https://unpkg.com/jcrop"></script>
  
  </head>

  <body>

     <%= render "shared/nav"%>
    <%= yield %>


     <%= render "shared/footer"%>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class = "notification is-success" roler = "alert" >
    <%= flash.now[:notice] %>
  </div>

  <% end %>

  <% if flash[:alert] %>
  <div class = "notification is-danger" role = "alert">
    <%= flash.now[:alert] %>
  </div>
  <% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<body class = "d-flex flex-column min-vh-100" >
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Event.com
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Venue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Hotel</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Car-rental</a>
          </p>
          <p>
            <a href="#!" class="text-reset">All-Event Coverds</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:

  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
</body>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg"  style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Event-Booker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <% if user_signed_in? && current_user[:role] == "user" %>
                      <li class= "nav-items">
                      <%= link_to "Bookings",bookings_path,class: "nav-link active"%>
                      </li>

                      <li class= "nav-items">
                      <%= link_to "GetAQuote",new_quote_path,class: "nav-link active"%>
                      </li>

                      <li class="nav-item">
                        <%= link_to "Logout",destroy_user_session_path,method: :delete,class: "nav-link active"%>
                      </li>
       
                      <% else %>
                      <li class="nav-item">
                        <%= link_to "LogIn",new_user_session_path,class: "nav-link active"%>
                      </li>
                      <li class="nav-item">
                        <%= link_to "SignUp",new_user_registration_path,class: "nav-link active"%>
                      </li>
        <% end %>
        <% if user_signed_in? && current_user[:role] == "vendor"%>
             <li class="nav-item">
                        <%= link_to "Logout",destroy_user_session_path,method: :delete,class: "nav-link active"%>
                      </li>
        <% end %>


      </ul>
    </div>
  </div>
</nav>