config/routes.rb
Rails.application.routes.draw do
  get 'quotes/new'
  resources :quotes
  post 'checkout/create' => 'checkouts#create', as: "checkout_create"
  post "/stripe_webhooks",to:"webhooks#create"
  # get "checkouts", to: "checkouts#show"
  # get "billing", to: "billing#show"

    resources :category do
        resources  :subcategory do
          resources :childs 
        end
    end


  resources :vendors
  resources :bookings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # patch '/users', to: "registrations#update"
  # delete '/users', to: "registrations@destroy"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' ,registrations:"registrations"} do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/edit' => 'devise/sessions#edit'
    # patch 'users/update'=> 'devise/sessions#update'
  end


  # devise_for :users,:controllers=>{registrations:"registrations"} do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  resources :events
  root to: 'homes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :place,:event_date,presence: true
  # validates_uniqueness_of :event_date, :on => :message => "must be unique"
 
  belongs_to :event 
  belongs_to :vendor
  belongs_to :user
  belongs_to :subcategory
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  # has_and_belongs_to_many :subcategories
  has_many :categorysubcategories
  has_many :subcategories, through: :categorysubcategories
  belongs_to :event
  has_many :bookings
end

app/models/categorysubcategory.rb
class Categorysubcategory < ApplicationRecord
  belongs_to :category
  belongs_to :subcategory
end

app/models/checkout.rb
class Checkout < ApplicationRecord
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :subcategory
end

app/models/event.rb
class Event < ApplicationRecord
    #  has_ancestry ancestry_column: :parent_id ## if you've used a different column name
    belongs_to :vendor
    
    has_many :EventVendors
    has_many :vendors, through: :EventVendors
    has_many :bookings, dependent: :destroy
    has_many :categories
end

app/models/event_vendor.rb
class EventVendor < ApplicationRecord
  belongs_to :event
  belongs_to :vendor
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :name,:email,:phone,:date,:budget,:comment,:event_id,presence: true
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  # belongs_to :category
  # has_and_belongs_to_many :categories
  has_many :categorysubcategories
  has_many :categories,through: :categorysubcategories, class_name: "Categorysubcategory", foreign_key: 'category_id'
  has_many :childs
  has_many :bookings

  after_create do
    product=Stripe::Product.create(name: name)
    price = Stripe::Price.create(product: product,unit_amount: self.price.to_i*100,currency:"inr")
    update(stripe_product_id: product.id,stripe_price_id: price.id)
 end
 
end

app/models/user.rb
class User < ApplicationRecord
  # include Pay::Billable
  # pay_customer
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and 
  attr_accessor :role

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  after_create :set_stripe_id

  # after_update :crop_image
  after_update :crop_image, if: :image_present


  validates :email,:fname,:lname,:dob, presence: true
  has_many :vendors
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable,:omniauthable, :registerable,
         :recoverable, :rememberable, :validatable
         
  mount_uploader :image, ImageUploader
  
  enum role: {"user"=>0, "vendor"=>1, "admin"=>2}

  def crop_image 
    binding.pry
    image.recreate_versions! if crop_x.present? && self.image.size > 0
  end

  def image_present
    self.image.size > 0
  end


  def self.from_omniauth(auth)
    
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.fname = auth.info.name   # assuming the user model has a name
      # user.image =s auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end


  private
  def set_stripe_id
    debugger
    if self.role == 'user'
      customer = Stripe::Customer.create(email:email, name:fname)
      self.update(stripe_customer_id: customer.id)
    end
  end


end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :user
  
  has_many :bookings, dependent: :destroy
  # has_many :events
  has_many :EventVendors
  has_many :events, through: :EventVendors

  validates :description,:address,:phone,:nearest_landmark,:website,:established_in, presence: true
  validates :user_id, uniqueness: true 
end

app/controllers/childs_controller.rb
class ChildsController < ApplicationController

  def index
    @subcategory = Subcategory.find(params[:subcategory_id])
    @child = @subcategory.childs
    respond_to do |format|
      format.js
    end
  end

  def show
    
  end

  def new
  end

  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.all;
    
    # @event = Event.where(parent_id: params[:parent_id]).to_a
 


  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_vendor

  def index
    # debugger
    @booking = Booking.all
    @vendor
    @event = Event.all
  end

  private

  def set_vendor
    if(user_signed_in? && current_user.role == "vendor")
      @vendor = Vendor.find_by(:user_id => current_user.id)
    end
  end


end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def index
    @vendors = Vendor.all
    @categories = Category.find(params[:category_id])
    @event = @categories.event
    @events = @event.id
    @eventVendor = @event.vendors
    # debugger
    # @v = Vendor.find()
  end

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.create!(vendor_params)
    # respond_to do |format|
    if @vendor.save
      flash[:notice] = "Account Created Successfully"
      redirect_to root_path
      # format.js
    else
      flash[:alert] = "Not Created Account"
      redirect_to root_path
    end

  end

  def show
    
    @v = Event.find_by(id: params[:id])
    # debugger
  end

  private

  def vendor_params
    params.require(:vendor).permit(:doc,:description,:address,:phone,:nearest_landmark,:email,:website,:established_in, :user_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_new.html.erb
<h4>Vendors Details</h4>

<%= form_with(model: @vendor,local: false) do |f| %>
  
      <div class="modal-body">
                    <div class="form-control">
                        <%= f.label :Description%>
                        <%= f.text_field :description%>
                     </div>
                    <div class="form-control">

                        <%= f.label :Phone%>
                        <%= f.telephone_field :phone%>
                    </div>
                     <div class="form-control">
                      <%= f.label :Address%>
                      <%= f.text_field :address%>
                    </div>
                    <div class="form-control">
                      <%= f.label :Landmark%>
                      <%= f.text_field :nearest_landmark%>
                    </div>

                    <div class="form-control">
                      <%= f.label :Website%>
                      <%= f.url_field :website%>
                    </div>
                    <div class="form-control">
                      <%= f.label :Established%>
                      <%= f.date_field :established_in%>
                      <%= f.hidden_field :user_id, value: current_user.id %>
                    </div>
                    <div class = "form-control">
                      <%= f.collection_select(:categories,Category.all,:id,:name) %>
                      <%= f.collection_select(:subcategories,Subcategory.all,:id,:name) %>
                    </div>
                    <div class="field">
                      <%= f.label :GSTCertificate %>
                      <%= f.file_field :doc %>
                    </div>
      </div>
     
      <div class="modal-footer">
        <%= f.submit "Fill Details",class:"btn btn-primary"%>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        
      </div>

 
<% end %>

app/views/vendors/create.js.erb
alert("Post Created");

app/views/vendors/index.html.erb
<h1>Vendors</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Address</th>
      <th scope = "col">Action</th> 
    </tr>
  </thead>
  <tbody>
<% @eventVendor.each do |v|%>
    <tr>
      <th scope="row">1</th>
      <td><%= v.user.fname %>  <%= v.user.lname %> </td>
      <td><%= v.description%></td>
      <td><%= v.website%></td>
      <td><%=link_to "Submit Booking", new_booking_path(:event_id => v.id, :user_id=> current_user.id,:vendor_id=> v.id,:category_id=>params[:category_id],:subcategory_id=>params[:subcategory_id])  %></td>
      <%# <td><%=button_to "Submit Payment", bookings_path(:event_id => @v.id, :user_id=> current_user.id,:vendor_id=>v.id),data: { bs_toggle: 'modal',bs_target: "#newBooking",remote: true }%> 
      <%# <td><%= button_to 'BookNow', {:controller => "bookings", :action => "create", :event_id => @v.id, :user_id=> current_user.id,:vendor_id=>v.id } , :method=>:post  %> 
    </tr>
  </tbody>
<%end%>

</table>

app/views/vendors/new.html.erb
<h4>Vendors Details</h4>

<%= form_with(model: @vendor,local: false) do |f| %>
  
      <div class="modal-body">
                    <div class="form-control">
                        <%= f.label :Description%>
                        <%= f.text_field :description%>
                     </div>
                    <div class="form-control">

                        <%= f.label :Phone%>
                        <%= f.telephone_field :phone%>
                    </div>
                     <div class="form-control">
                      <%= f.label :Address%>
                      <%= f.text_field :address%>
                    </div>
                    <div class="form-control">
                      <%= f.label :Landmark%>
                      <%= f.text_field :nearest_landmark%>
                    </div>

                    <div class="form-control">
                      <%= f.label :Website%>
                      <%= f.url_field :website%>
                    </div>
                    <div class="form-control">
                      <%= f.label :Established%>
                      <%= f.date_field :established_in%>
                      <%= f.hidden_field :user_id, value: current_user.id %>
                    </div>
                    <div class = "form-control">
                      <%= f.collection_select(:categories,Event.all,:id,:name) %>
                      <%= f.collection_select(:subcategories,Subcategory.all,:id,:name) %>
                    </div>
                    <div class="field">
                      <%= f.label :GSTCertificate %>
                      <%= f.file_field :doc %>
                    </div>  
      </div>
     
      <div class="modal-footer">
        <%= f.submit "Fill Details",class:"btn btn-primary"%>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        
      </div>

 
<% end %>

app/views/vendors/new.js.erb
<%# $("#newVendorForm").html("<%= escape_javascript render('new',vendor:@vendor)%>"); %>

app/views/vendors/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Address</th>
      <th scope = "col">Action</th> 
    </tr>
  </thead>
  <tbody>
<% @v.vendors.each do |v|%>
    <tr>
      <th scope="row">1</th>
      <td><%= v.user.fname %>  <%= v.user.lname %> </td>
      <td><%= v.description%></td>
      <td><%= v.website%></td>
      <td><%=link_to "Submit Booking", new_booking_path(:event_id => @v.id, :user_id=> current_user.id,:vendor_id=>v.id)%></td> 
      <%# <td><%=button_to "Submit Payment", bookings_path(:event_id => @v.id, :user_id=> current_user.id,:vendor_id=>v.id),data: { bs_toggle: 'modal',bs_target: "#newBooking",remote: true }%> %>
      <%# <td><%= button_to 'BookNow', {:controller => "bookings", :action => "create", :event_id => @v.id, :user_id=> current_user.id,:vendor_id=>v.id } , :method=>:post  %> %>
    </tr>
  </tbody>
<%end%>

</table>






<div class="modal fade" id="newBooking" tabindex="-1" aria-labelledby="newBookingLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newVendorLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id = "newBookingForm">
      </div>
     
    </div>
  </div>
</div>











<script>
  var stripe = Stripe('<%= Rails.application.credentials.stripe[:public_key]%>');
  
</script>